#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="carbonplan-gcp-us-cental-1"
export SCRATCH="gs://carbonplan-scratch"
export CARBONPLAN_DATA="gs://carbonplan-data"

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
