#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="carbonplan.2i2c.cloud/"
export SCRATCH="s3://carbonplan-scratch"
export CARBONPLAN_DATA="gs://carbonplan-data"

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
